apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppconboarding-workflow-api
  namespace: default
spec:
  # replicas: 5
  selector:
    matchLabels:
      app: ppconboarding-workflow-api
  template:
    metadata:
      labels:
        app: ppconboarding-workflow-api
    spec:
      containers:
        - name: temporal-demo-api
          image: us.gcr.io/cbregcpsandbox/ppconboarding-workflow:default
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILE
              value: ERROR
            - name: WORKER
              value: ERROR
            - name: TEMPORAL_SVC_ADDR
              value: "temporaltest-frontend:7233"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ppconboarding-workflow-api-svc
spec:
  selector:
    app: ppconboarding-workflow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
