apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-demo-worker
  namespace: default
spec:
  # replicas: 5
  selector:
    matchLabels:
      app: temporal-demo-worker
  template:
    metadata:
      labels:
        app: temporal-demo-worker
    spec:
      containers:
        - name: temporal-demo-worker
          image: us.gcr.io/cbregcpsandbox/temporal-springboot-demo:default
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILE
              value: ERROR
            - name: WORKER
              value: WORKER
            - name: TEMPORAL_SVC_ADDR
              value: "temporaltest-frontend:7233"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
