apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppconboarding-workflow-worker
  namespace: default
spec:
  # replicas: 5
  selector:
    matchLabels:
      app: ppconboarding-workflow-worker
  template:
    metadata:
      labels:
        app: ppconboarding-workflow-worker
    spec:
      containers:
        - name: ppconboarding-workflow-worker
          image: us.gcr.io/cbregcpsandbox/ppconboarding-workflow:default
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILE
              value: ERROR
            - name: WORKER
              value: WORKER
            - name: TEMPORAL_SVC_ADDR
              value: "temporaltest-frontend:7233"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
